from typing import Any, Dict, Optional

from langchain_core.pydantic_v1 import BaseModel, Field


class GraphState(BaseModel):
    """Represents the state of our graph.

    Attributes:
        person: The name of the person to generate a bio for.
        bio: An optional dictionary containing the bio generated by the LLM for the person.
        scrapped_data: An optional dictionary containing the scraped data documents for the person.
        linkedin_url: An optional string containing the URL of the person on LinkedIn.
    """

    person: str = Field(..., description="The person to generate a bio for")
    bio: Optional[Dict[str, str]] = None
    scrapped_data: Optional[Dict[str, Any]] = None
    linkedin_url: Optional[str] = ""
