from typing import Any, Dict, List, Optional

from langchain_core.pydantic_v1 import BaseModel, Field


class GraphState(BaseModel):
    """Represents the state of our graph.

    Attributes:
        person: person
        bio: bio generated by LLM of the person
        scrapped_data: list of scrapped_data documents
        linkedin_url: url of the person on LinkedIn
    """

    person: str = Field(..., description="The person to generate a bio for")
    bio: Optional[Dict[str, str]] = None
    scrapped_data: Optional[List[Any]] = []
    linkedin_url: Optional[str] = ""
